services:
  triviaapp:
    build:
      context: .
      dockerfile: TriviaApp.Docker/dockerfile
    ports:
      - 8080:8080
    environment:
      - Redis__Configuration=redis:6379
    networks:
      - triviaapp_network

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - triviaapp_network

networks:
  triviaapp_network:
    driver: bridge
